import {
  createContext,
  useCallback,
  useContext,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Language = "en" | "zh";

const LANGUAGE_STORAGE_KEY = "paperclip.language";

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar
    "sidebar.newIssue": "New Issue",
    "sidebar.dashboard": "Dashboard",
    "sidebar.inbox": "Inbox",
    "sidebar.issues": "Issues",
    "sidebar.goals": "Goals",
    "sidebar.work": "Work",
    "sidebar.projects": "Projects",
    "sidebar.agents": "Agents",
    "sidebar.org": "Org",
    "sidebar.costs": "Costs",
    "sidebar.activity": "Activity",
    "sidebar.company": "Company",
    "sidebar.settings": "Settings",
    "sidebar.selectCompany": "Select company",
    "sidebar.documentation": "Documentation",
    // InstanceSidebar
    "instanceSidebar.title": "Instance Settings",
    "instanceSidebar.heartbeats": "Heartbeats",
    "instanceSidebar.plugins": "Plugins",
    // CompanyRail
    "companyRail.addCompany": "Add company",
    // MobileBottomNav
    "mobileNav.home": "Home",
    "mobileNav.issues": "Issues",
    "mobileNav.create": "Create",
    "mobileNav.agents": "Agents",
    "mobileNav.inbox": "Inbox",
    "mobileNav.ariaLabel": "Mobile navigation",
    // CommandPalette
    "cmd.placeholder": "Search issues, agents, projects...",
    "cmd.noResults": "No results found.",
    "cmd.actions": "Actions",
    "cmd.createIssue": "Create new issue",
    "cmd.createAgent": "Create new agent",
    "cmd.createProject": "Create new project",
    "cmd.pages": "Pages",
    "cmd.dashboard": "Dashboard",
    "cmd.inbox": "Inbox",
    "cmd.issues": "Issues",
    "cmd.projects": "Projects",
    "cmd.goals": "Goals",
    "cmd.agents": "Agents",
    "cmd.costs": "Costs",
    "cmd.activity": "Activity",
    "cmd.issuesGroup": "Issues",
    "cmd.agentsGroup": "Agents",
    "cmd.projectsGroup": "Projects",
    // NewIssueDialog
    "issue.new": "New issue",
    "issue.titlePlaceholder": "Issue title",
    "issue.for": "For",
    "issue.assignee": "Assignee",
    "issue.searchAssignees": "Search assignees...",
    "issue.noAssignees": "No assignees found.",
    "issue.noAssignee": "No assignee",
    "issue.in": "in",
    "issue.project": "Project",
    "issue.searchProjects": "Search projects...",
    "issue.noProjects": "No projects found.",
    "issue.noProject": "No project",
    "issue.isolatedCheckout": "Use isolated issue checkout",
    "issue.isolatedCheckoutDesc": "Create an issue-specific execution workspace instead of using the project's primary checkout.",
    "issue.defaultModel": "Default model",
    "issue.searchModels": "Search models...",
    "issue.noModels": "No models found.",
    "issue.model": "Model",
    "issue.thinkingEffort": "Thinking effort",
    "issue.default": "Default",
    "issue.low": "Low",
    "issue.medium": "Medium",
    "issue.high": "High",
    "issue.minimal": "Minimal",
    "issue.max": "Max",
    "issue.enableChrome": "Enable Chrome (--chrome)",
    "issue.descriptionPlaceholder": "Add description...",
    "issue.documents": "Documents",
    "issue.removeDocument": "Remove document",
    "issue.attachments": "Attachments",
    "issue.removeAttachment": "Remove attachment",
    "issue.statusBacklog": "Backlog",
    "issue.statusTodo": "Todo",
    "issue.statusInProgress": "In Progress",
    "issue.statusInReview": "In Review",
    "issue.statusDone": "Done",
    "issue.priorityCritical": "Critical",
    "issue.priorityHigh": "High",
    "issue.priorityMedium": "Medium",
    "issue.priorityLow": "Low",
    "issue.priority": "Priority",
    "issue.labels": "Labels",
    "issue.upload": "Upload",
    "issue.startDate": "Start date",
    "issue.dueDate": "Due date",
    "issue.discardDraft": "Discard Draft",
    "issue.creating": "Creating issue...",
    "issue.createError": "Failed to create issue. Try again.",
    "issue.create": "Create Issue",
    "issue.creatingShort": "Creating...",
    // NewAgentDialog
    "agent.new": "Add a new agent",
    "agent.recommendation": "We recommend letting your CEO handle agent setup — they know the org structure and can configure reporting, permissions, and adapters.",
    "agent.askCeo": "Ask the CEO to create a new agent",
    "agent.advancedConfig": "I want advanced configuration myself",
    "agent.chooseAdapter": "Choose your adapter type for advanced setup.",
    "agent.back": "Back",
    "agent.recommended": "Recommended",
    "agent.creating": "Creating...",
    // NewProjectDialog
    "project.new": "New project",
    "project.namePlaceholder": "Project name",
    "project.descriptionPlaceholder": "Add description...",
    "project.workspaceQuestion": "Where will work be done on this project?",
    "project.workspaceHint": "Add local folder and/or GitHub repo workspace hints.",
    "project.localFolder": "A local folder",
    "project.localFolderHint": "Use a full path on this machine.",
    "project.githubRepo": "A github repo",
    "project.githubRepoHint": "Paste a GitHub URL.",
    "project.both": "Both",
    "project.bothHint": "Configure local + repo hints.",
    "project.localFolderLabel": "Local folder (full path)",
    "project.githubRepoLabel": "GitHub repo URL",
    "project.localPathError": "Local folder must be a full absolute path.",
    "project.githubUrlError": "Repo workspace must use a valid GitHub repo URL.",
    "project.addGoal": "+ Goal",
    "project.goalLabel": "Goal",
    "project.noGoal": "No goal",
    "project.allGoalsSelected": "All goals already selected.",
    "project.targetDate": "Target date",
    "project.createError": "Failed to create project.",
    "project.create": "Create project",
    "project.creating": "Creating…",
    // NewGoalDialog
    "goal.new": "New goal",
    "goal.newSub": "New sub-goal",
    "goal.titlePlaceholder": "Goal title",
    "goal.descriptionPlaceholder": "Add description...",
    "goal.levelCompany": "Company",
    "goal.levelTeam": "Team",
    "goal.levelAgent": "Agent",
    "goal.levelTask": "Task",
    "goal.parentLabel": "Parent goal",
    "goal.noParent": "No parent",
    "goal.create": "Create goal",
    "goal.createSub": "Create sub-goal",
    "goal.creating": "Creating…",
    // Layout
    "layout.skipToContent": "Skip to Main Content",
    // Dashboard
    "dashboard.noAgents": "You have no agents.",
    "dashboard.createOne": "Create one here",
    "dashboard.agentsEnabled": "Agents Enabled",
    "dashboard.running": "running",
    "dashboard.paused": "paused",
    "dashboard.errors": "errors",
    "dashboard.tasksInProgress": "Tasks In Progress",
    "dashboard.open": "open",
    "dashboard.blocked": "blocked",
    "dashboard.monthSpend": "Month Spend",
    "dashboard.unlimitedBudget": "Unlimited budget",
    "dashboard.budgetOf": "of",
    "dashboard.budget": "budget",
    "dashboard.pendingApprovals": "Pending Approvals",
    "dashboard.awaitingReview": "Awaiting board review",
    "dashboard.runActivity": "Run Activity",
    "dashboard.issuesByPriority": "Issues by Priority",
    "dashboard.issuesByStatus": "Issues by Status",
    "dashboard.successRate": "Success Rate",
    "dashboard.last14Days": "Last 14 days",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.recentTasks": "Recent Tasks",
    "dashboard.noTasks": "No tasks yet.",
    "dashboard.welcomeMessage": "Welcome to Paperclip. Set up your first company and agent to get started.",
    "dashboard.getStarted": "Get Started",
    "dashboard.selectCompany": "Create or select a company to view the dashboard.",
    // ActiveAgentsPanel
    "agents.liveNow": "Live now",
    "agents.finished": "Finished",
    "agents.started": "Started",
    "agents.waitingTranscript": "Waiting for transcript parsing...",
    "agents.waitingOutput": "Waiting for output...",
    "agents.noTranscript": "No transcript captured.",
    "agents.title": "Agents",
    "agents.noRecentRuns": "No recent agent runs.",
    // Misc
    "misc.loading": "Loading...",
    "misc.error": "Something went wrong",
    "misc.notFound": "Not found",
  },
  zh: {
    // Sidebar
    "sidebar.newIssue": "新建任务",
    "sidebar.dashboard": "仪表盘",
    "sidebar.inbox": "收件箱",
    "sidebar.issues": "任务",
    "sidebar.goals": "目标",
    "sidebar.work": "工作",
    "sidebar.projects": "项目",
    "sidebar.agents": "代理",
    "sidebar.org": "组织",
    "sidebar.costs": "费用",
    "sidebar.activity": "活动记录",
    "sidebar.company": "公司",
    "sidebar.settings": "设置",
    "sidebar.selectCompany": "选择公司",
    "sidebar.documentation": "文档",
    // InstanceSidebar
    "instanceSidebar.title": "实例设置",
    "instanceSidebar.heartbeats": "心跳",
    "instanceSidebar.plugins": "插件",
    // CompanyRail
    "companyRail.addCompany": "添加公司",
    // MobileBottomNav
    "mobileNav.home": "首页",
    "mobileNav.issues": "任务",
    "mobileNav.create": "新建",
    "mobileNav.agents": "代理",
    "mobileNav.inbox": "收件箱",
    "mobileNav.ariaLabel": "移动端导航",
    // CommandPalette
    "cmd.placeholder": "搜索任务、代理、项目...",
    "cmd.noResults": "未找到结果。",
    "cmd.actions": "操作",
    "cmd.createIssue": "新建任务",
    "cmd.createAgent": "新建代理",
    "cmd.createProject": "新建项目",
    "cmd.pages": "页面",
    "cmd.dashboard": "仪表盘",
    "cmd.inbox": "收件箱",
    "cmd.issues": "任务",
    "cmd.projects": "项目",
    "cmd.goals": "目标",
    "cmd.agents": "代理",
    "cmd.costs": "费用",
    "cmd.activity": "活动记录",
    "cmd.issuesGroup": "任务",
    "cmd.agentsGroup": "代理",
    "cmd.projectsGroup": "项目",
    // NewIssueDialog
    "issue.new": "新建任务",
    "issue.titlePlaceholder": "任务标题",
    "issue.for": "指派给",
    "issue.assignee": "负责人",
    "issue.searchAssignees": "搜索负责人...",
    "issue.noAssignees": "未找到负责人。",
    "issue.noAssignee": "无负责人",
    "issue.in": "在",
    "issue.project": "项目",
    "issue.searchProjects": "搜索项目...",
    "issue.noProjects": "未找到项目。",
    "issue.noProject": "无项目",
    "issue.isolatedCheckout": "使用独立任务工作区",
    "issue.isolatedCheckoutDesc": "为此任务创建独立的执行工作区，而非使用项目的主工作区。",
    "issue.defaultModel": "默认模型",
    "issue.searchModels": "搜索模型...",
    "issue.noModels": "未找到模型。",
    "issue.model": "模型",
    "issue.thinkingEffort": "思考强度",
    "issue.default": "默认",
    "issue.low": "低",
    "issue.medium": "中",
    "issue.high": "高",
    "issue.minimal": "最低",
    "issue.max": "最高",
    "issue.enableChrome": "启用 Chrome (--chrome)",
    "issue.descriptionPlaceholder": "添加描述...",
    "issue.documents": "文档",
    "issue.removeDocument": "移除文档",
    "issue.attachments": "附件",
    "issue.removeAttachment": "移除附件",
    "issue.statusBacklog": "待办",
    "issue.statusTodo": "计划中",
    "issue.statusInProgress": "进行中",
    "issue.statusInReview": "审核中",
    "issue.statusDone": "已完成",
    "issue.priorityCritical": "紧急",
    "issue.priorityHigh": "高",
    "issue.priorityMedium": "中",
    "issue.priorityLow": "低",
    "issue.priority": "优先级",
    "issue.labels": "标签",
    "issue.upload": "上传",
    "issue.startDate": "开始日期",
    "issue.dueDate": "截止日期",
    "issue.discardDraft": "丢弃草稿",
    "issue.creating": "创建任务中...",
    "issue.createError": "创建任务失败，请重试。",
    "issue.create": "创建任务",
    "issue.creatingShort": "创建中...",
    // NewAgentDialog
    "agent.new": "添加新代理",
    "agent.recommendation": "建议让您的 CEO 来处理代理设置——他们了解组织结构，可以配置汇报关系、权限和适配器。",
    "agent.askCeo": "让 CEO 创建新代理",
    "agent.advancedConfig": "我想自己进行高级配置",
    "agent.chooseAdapter": "选择高级设置的适配器类型。",
    "agent.back": "返回",
    "agent.recommended": "推荐",
    "agent.creating": "创建中...",
    // NewProjectDialog
    "project.new": "新建项目",
    "project.namePlaceholder": "项目名称",
    "project.descriptionPlaceholder": "添加描述...",
    "project.workspaceQuestion": "这个项目的工作将在哪里进行？",
    "project.workspaceHint": "添加本地文件夹和/或 GitHub 仓库工作区提示。",
    "project.localFolder": "本地文件夹",
    "project.localFolderHint": "使用此机器上的完整路径。",
    "project.githubRepo": "GitHub 仓库",
    "project.githubRepoHint": "粘贴 GitHub URL。",
    "project.both": "两者都有",
    "project.bothHint": "配置本地 + 仓库提示。",
    "project.localFolderLabel": "本地文件夹（完整路径）",
    "project.githubRepoLabel": "GitHub 仓库 URL",
    "project.localPathError": "本地文件夹必须是完整的绝对路径。",
    "project.githubUrlError": "仓库工作区必须使用有效的 GitHub 仓库 URL。",
    "project.addGoal": "+ 目标",
    "project.goalLabel": "目标",
    "project.noGoal": "无目标",
    "project.allGoalsSelected": "所有目标已选择。",
    "project.targetDate": "目标日期",
    "project.createError": "创建项目失败。",
    "project.create": "创建项目",
    "project.creating": "创建中…",
    // NewGoalDialog
    "goal.new": "新建目标",
    "goal.newSub": "新建子目标",
    "goal.titlePlaceholder": "目标标题",
    "goal.descriptionPlaceholder": "添加描述...",
    "goal.levelCompany": "公司",
    "goal.levelTeam": "团队",
    "goal.levelAgent": "代理",
    "goal.levelTask": "任务",
    "goal.parentLabel": "父目标",
    "goal.noParent": "无父目标",
    "goal.create": "创建目标",
    "goal.createSub": "创建子目标",
    "goal.creating": "创建中…",
    // Layout
    "layout.skipToContent": "跳转到主要内容",
    // Dashboard
    "dashboard.noAgents": "您还没有代理。",
    "dashboard.createOne": "在这里创建",
    "dashboard.agentsEnabled": "已启用代理",
    "dashboard.running": "运行中",
    "dashboard.paused": "已暂停",
    "dashboard.errors": "错误",
    "dashboard.tasksInProgress": "进行中的任务",
    "dashboard.open": "待处理",
    "dashboard.blocked": "已阻塞",
    "dashboard.monthSpend": "本月花费",
    "dashboard.unlimitedBudget": "无限预算",
    "dashboard.budgetOf": "占",
    "dashboard.budget": "预算",
    "dashboard.pendingApprovals": "待审批",
    "dashboard.awaitingReview": "等待审核",
    "dashboard.runActivity": "运行活动",
    "dashboard.issuesByPriority": "按优先级分类任务",
    "dashboard.issuesByStatus": "按状态分类任务",
    "dashboard.successRate": "成功率",
    "dashboard.last14Days": "最近 14 天",
    "dashboard.recentActivity": "最近活动",
    "dashboard.recentTasks": "最近任务",
    "dashboard.noTasks": "暂无任务。",
    "dashboard.welcomeMessage": "欢迎使用 Paperclip。创建您的第一个公司和代理以开始使用。",
    "dashboard.getStarted": "开始使用",
    "dashboard.selectCompany": "创建或选择一个公司以查看仪表盘。",
    // ActiveAgentsPanel
    "agents.liveNow": "实时",
    "agents.finished": "完成于",
    "agents.started": "开始于",
    "agents.waitingTranscript": "等待转录解析...",
    "agents.waitingOutput": "等待输出...",
    "agents.noTranscript": "未捕获到转录。",
    "agents.title": "代理",
    "agents.noRecentRuns": "暂无最近的代理运行记录。",
    // Misc
    "misc.loading": "加载中...",
    "misc.error": "出现错误",
    "misc.notFound": "未找到",
  },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

function resolveInitialLanguage(): Language {
  try {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored === "en" || stored === "zh") return stored;
  } catch {
    // ignore
  }
  return "en";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(resolveInitialLanguage);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    } catch {
      // ignore
    }
  }, []);

  const t = useCallback(
    (key: string): string => translations[language][key] ?? translations["en"][key] ?? key,
    [language],
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
